version: '3.6'

services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && rails server puma"
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:10.3-alpine
    volumes:
      - postgres_jokes:/var/lib/postgresql/data


volumes:
  postgres_jokes:


