version: '3.6'

services:
  web:
    build: .
    volumes:
      - bundle_cache:/bundle
      - ./:/app
      - type: tmpfs
        target: /app/tmp/pidds
    working_dir: /app
    command: rails server puma
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:10.3-alpine
    volumes:
      - postgres_jokes:/var/lib/postgresql/data


volumes:
  bundle_cache:
  postgres_jokes:


